version: '1.0'
services:
  # Gateway API
  skoole_gateway:
    container_name: skoole_gateway
    build:
      context: ./
      dockerfile: ./devops/docker/Dockerfile
    hostname: skoole_gateway
    ports:
      - 80:8080
    volumes:
      - ./skoole/gateway:/usr/src/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - skoole

  # Registry API
  skoole_registry:
    container_name: skoole_registry
    build:
      context: ./
      dockerfile: ./devops/docker/Dockerfile
    hostname: skoole_registry
    volumes:
      - ./skoole/registry_service:/usr/src/app
    networks:
      - skoole

  # Search API
  skoole_search:
    container_name: skoole_search
    build:
      context: ./
      dockerfile: ./devops/docker/Dockerfile
    hostname: skoole_search
    volumes:
      - ./skoole/search_service:/usr/src/app
    networks:
      - skoole

  # Forum API
  skoole_forum:
    container_name: skoole_forum
    build:
      context: ./
      dockerfile: ./devops/docker/Dockerfile
    hostname: skoole_forum
    volumes:
      - ./skoole/forum_service:/usr/src/app
    networks:
      - skoole

# Internal Networks
networks:
  skoole:
    name: skoole